# Generated by Django 3.1.3 on 2023-06-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230609_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='enrollment_id',
            new_name='enrollment',
        ),
    ]
